---
galaxy_info:
  role_name: common
  author: Patrick Godschalk
  description: Common server configuration
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  namespace: pgodschalk

dependencies: []
