---
- name: Apply sysctl settings
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: true

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  changed_when: true

- name: Restart fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted

- name: Restart postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted

- name: Update PAM
  ansible.builtin.command:
    cmd: pam-auth-update --package
  changed_when: true
